# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0emessages.proto\x12\x08messages\"P\n\rStatusMessage\x12!\n\x07modules\x18\x01 \x03(\x0b\x32\x10.messages.Module\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0b\n\x03mac\x18\x03 \x01(\x0c\"\xbf\x01\n\x06Module\x12,\n\x06status\x18\x01 \x03(\x0b\x32\x1c.messages.Module.StatusEntry\x12\x0e\n\x06ucount\x18\x02 \x01(\x05\x12\r\n\x05\x61lert\x18\x03 \x03(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\x05\x12\x11\n\tmodule_id\x18\x06 \x01(\t\x12\x15\n\rmodule_amount\x18\x07 \x01(\x05\x1a-\n\x0bStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"J\n\x0bTempMessage\x12\x1d\n\x05temps\x18\x01 \x03(\x0b\x32\x0e.messages.Temp\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0b\n\x03mac\x18\x03 \x01(\x0c\"A\n\x04Temp\x12\x11\n\tmodule_id\x18\x01 \x01(\t\x12&\n\x08temp_hum\x18\x02 \x03(\x0b\x32\x14.messages.TempDetail\"6\n\nTempDetail\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04temp\x18\x02 \x01(\x02\x12\x0b\n\x03hum\x18\x03 \x01(\x02\"M\n\x0cLightMessage\x12\x1f\n\x06lights\x18\x01 \x03(\x0b\x32\x0f.messages.Light\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0b\n\x03mac\x18\x03 \x01(\x0c\"\x86\x01\n\x05Light\x12\x11\n\tmodule_id\x18\x01 \x01(\t\x12\x36\n\x0clight_status\x18\x02 \x03(\x0b\x32 .messages.Light.LightStatusEntry\x1a\x32\n\x10LightStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xc0\x01\n\rUpdateService\x12;\n\x0cUpdateStatus\x12\x17.messages.StatusMessage\x1a\x12.messages.Response\x12\x37\n\nUpdateTemp\x12\x15.messages.TempMessage\x1a\x12.messages.Response\x12\x39\n\x0bUpdateLight\x12\x16.messages.LightMessage\x1a\x12.messages.Responseb\x06proto3'
)




_STATUSMESSAGE = _descriptor.Descriptor(
  name='StatusMessage',
  full_name='messages.StatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modules', full_name='messages.StatusMessage.modules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='messages.StatusMessage.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='messages.StatusMessage.mac', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=108,
)


_MODULE_STATUSENTRY = _descriptor.Descriptor(
  name='StatusEntry',
  full_name='messages.Module.StatusEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='messages.Module.StatusEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='messages.Module.StatusEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=302,
)

_MODULE = _descriptor.Descriptor(
  name='Module',
  full_name='messages.Module',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='messages.Module.status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ucount', full_name='messages.Module.ucount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alert', full_name='messages.Module.alert', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='messages.Module.address', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module_id', full_name='messages.Module.module_id', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module_amount', full_name='messages.Module.module_amount', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODULE_STATUSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=302,
)


_TEMPMESSAGE = _descriptor.Descriptor(
  name='TempMessage',
  full_name='messages.TempMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temps', full_name='messages.TempMessage.temps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='messages.TempMessage.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='messages.TempMessage.mac', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=378,
)


_TEMP = _descriptor.Descriptor(
  name='Temp',
  full_name='messages.Temp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_id', full_name='messages.Temp.module_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_hum', full_name='messages.Temp.temp_hum', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=445,
)


_TEMPDETAIL = _descriptor.Descriptor(
  name='TempDetail',
  full_name='messages.TempDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='messages.TempDetail.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='messages.TempDetail.temp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hum', full_name='messages.TempDetail.hum', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=501,
)


_LIGHTMESSAGE = _descriptor.Descriptor(
  name='LightMessage',
  full_name='messages.LightMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lights', full_name='messages.LightMessage.lights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='messages.LightMessage.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='messages.LightMessage.mac', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=580,
)


_LIGHT_LIGHTSTATUSENTRY = _descriptor.Descriptor(
  name='LightStatusEntry',
  full_name='messages.Light.LightStatusEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='messages.Light.LightStatusEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='messages.Light.LightStatusEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=717,
)

_LIGHT = _descriptor.Descriptor(
  name='Light',
  full_name='messages.Light',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_id', full_name='messages.Light.module_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='light_status', full_name='messages.Light.light_status', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LIGHT_LIGHTSTATUSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=717,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='messages.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='messages.Response.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=745,
)

_STATUSMESSAGE.fields_by_name['modules'].message_type = _MODULE
_MODULE_STATUSENTRY.containing_type = _MODULE
_MODULE.fields_by_name['status'].message_type = _MODULE_STATUSENTRY
_TEMPMESSAGE.fields_by_name['temps'].message_type = _TEMP
_TEMP.fields_by_name['temp_hum'].message_type = _TEMPDETAIL
_LIGHTMESSAGE.fields_by_name['lights'].message_type = _LIGHT
_LIGHT_LIGHTSTATUSENTRY.containing_type = _LIGHT
_LIGHT.fields_by_name['light_status'].message_type = _LIGHT_LIGHTSTATUSENTRY
DESCRIPTOR.message_types_by_name['StatusMessage'] = _STATUSMESSAGE
DESCRIPTOR.message_types_by_name['Module'] = _MODULE
DESCRIPTOR.message_types_by_name['TempMessage'] = _TEMPMESSAGE
DESCRIPTOR.message_types_by_name['Temp'] = _TEMP
DESCRIPTOR.message_types_by_name['TempDetail'] = _TEMPDETAIL
DESCRIPTOR.message_types_by_name['LightMessage'] = _LIGHTMESSAGE
DESCRIPTOR.message_types_by_name['Light'] = _LIGHT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusMessage = _reflection.GeneratedProtocolMessageType('StatusMessage', (_message.Message,), {
  'DESCRIPTOR' : _STATUSMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.StatusMessage)
  })
_sym_db.RegisterMessage(StatusMessage)

Module = _reflection.GeneratedProtocolMessageType('Module', (_message.Message,), {

  'StatusEntry' : _reflection.GeneratedProtocolMessageType('StatusEntry', (_message.Message,), {
    'DESCRIPTOR' : _MODULE_STATUSENTRY,
    '__module__' : 'messages_pb2'
    # @@protoc_insertion_point(class_scope:messages.Module.StatusEntry)
    })
  ,
  'DESCRIPTOR' : _MODULE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.Module)
  })
_sym_db.RegisterMessage(Module)
_sym_db.RegisterMessage(Module.StatusEntry)

TempMessage = _reflection.GeneratedProtocolMessageType('TempMessage', (_message.Message,), {
  'DESCRIPTOR' : _TEMPMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.TempMessage)
  })
_sym_db.RegisterMessage(TempMessage)

Temp = _reflection.GeneratedProtocolMessageType('Temp', (_message.Message,), {
  'DESCRIPTOR' : _TEMP,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.Temp)
  })
_sym_db.RegisterMessage(Temp)

TempDetail = _reflection.GeneratedProtocolMessageType('TempDetail', (_message.Message,), {
  'DESCRIPTOR' : _TEMPDETAIL,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.TempDetail)
  })
_sym_db.RegisterMessage(TempDetail)

LightMessage = _reflection.GeneratedProtocolMessageType('LightMessage', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.LightMessage)
  })
_sym_db.RegisterMessage(LightMessage)

Light = _reflection.GeneratedProtocolMessageType('Light', (_message.Message,), {

  'LightStatusEntry' : _reflection.GeneratedProtocolMessageType('LightStatusEntry', (_message.Message,), {
    'DESCRIPTOR' : _LIGHT_LIGHTSTATUSENTRY,
    '__module__' : 'messages_pb2'
    # @@protoc_insertion_point(class_scope:messages.Light.LightStatusEntry)
    })
  ,
  'DESCRIPTOR' : _LIGHT,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.Light)
  })
_sym_db.RegisterMessage(Light)
_sym_db.RegisterMessage(Light.LightStatusEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.Response)
  })
_sym_db.RegisterMessage(Response)


_MODULE_STATUSENTRY._options = None
_LIGHT_LIGHTSTATUSENTRY._options = None

_UPDATESERVICE = _descriptor.ServiceDescriptor(
  name='UpdateService',
  full_name='messages.UpdateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=748,
  serialized_end=940,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateStatus',
    full_name='messages.UpdateService.UpdateStatus',
    index=0,
    containing_service=None,
    input_type=_STATUSMESSAGE,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTemp',
    full_name='messages.UpdateService.UpdateTemp',
    index=1,
    containing_service=None,
    input_type=_TEMPMESSAGE,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateLight',
    full_name='messages.UpdateService.UpdateLight',
    index=2,
    containing_service=None,
    input_type=_LIGHTMESSAGE,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATESERVICE)

DESCRIPTOR.services_by_name['UpdateService'] = _UPDATESERVICE

# @@protoc_insertion_point(module_scope)
